# Generated by Django 4.1.7 on 2023-03-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JSONPrueba', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacion',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='estacion',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
